# Dependencies
markdown:         kramdown
highlighter:      rouge

# Permalinks
permalink:        pretty

# Setup
title:               's3a'
tagline:             'testing times'
description:         'The musing of a parent, photographer and software tester'
url:                 'https:///jlwatts.github.io'
baseurl:          'https:///jlwatts.github.io/'

author:
  name:           'Jonathan'
  url:            https://twitter.com/whatie

paginate:         5

# Custom vars
version:          2.1.0

github:
  repo:           https://github.com/poole/hyde
  
github.repository_url: https://github.com/jlwatts/jlwatts.github.io

# static paths
defaults:
  - scope:
      path: "assets/img"
    values:
      image: true
